version: "3.9"
services:
  frontend:
    container_name: nginx-frontend-app
    image: mymaestro_frontend
    restart: always
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - .env
    volumes:
      - ./infra/nginx/conf/:/etc/nginx/conf.d/:ro
    networks:
      - natbridge
    ports:
      - 80:80
      - 443:443

  backend:
    container_name: node-app
    image: mymaestro_backend
    restart: always
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    networks:
      - natbridge

networks:
  natbridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/24
